name: lm_club
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  form_field_validator: ^1.1.0
  shared_preferences: ^2.2.2
  curved_navigation_bar: ^1.0.3
  dotted_border: ^2.1.0
  searchfield: ^0.8.7
  http: ^0.13.6
  equatable: ^2.0.5
  injectable: ^2.3.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.3+1
  build_runner: ^2.1.7
  get_it: ^7.2.0
  logger: ^2.0.2+1
  retrofit: ^4.1.0
  share_plus: ^7.2.1
  carousel_slider: ^5.0.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  accordion: ^2.6.0
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.1.1
  # inkblob_navigation_bar: ^0.1.2
  url_launcher: ^6.2.4
  http_parser: ^4.0.2
  permission_handler: ^11.0.1
  clipboard: ^0.1.3
  intl: ^0.18.1
  timeago: ^3.6.1
  qlevar_router: ^1.10.2
  video_player: ^2.8.5
  text_scroll: ^0.2.0
  flutter_html: ^3.0.0-beta.2
  timezone: ^0.9.3
  easy_refresh: ^3.4.0
  json_annotation: ^4.9.0
  pinput: ^5.0.0
  flutter_paypal_payment: ^1.0.8
  webview_flutter: ^4.5.0
  html: ^0.15.4
  # flutter_share_me: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  freezed: ^2.2.0
  json_serializable: any
  test: ^1.24.3

flutter:
  fonts:
    - family: NeueHaasGroteskTextPro
      fonts:
        - asset: assets/fonts/NeueHaasGroteskTextPro.ttf
        - asset: assets/fonts/NeueHaasGroteskTextProBold.ttf
          weight: 900
        - asset: assets/fonts/NeueHaasGroteskTextProMedium.ttf
          weight: 500
        - asset: assets/fonts/NeueHaasGroteskTextProItalic.ttf
          style: italic

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cards/
